### PR TITLE
Check command-arguments even without action handler

### LINKED ISSUE #1493: Required non-option arguments only checked with .action()?
It appears that `commander@7.2.0` only checks `.arguments()` for the top-level command if `.action()` is given.  For example:

```js
#!/usr/bin/env node
const { Command } = require('commander');
const command = new Command();
command
  .arguments('<source>')
  .allowExcessArguments(false)
  .description('do something with a single source file')
  .action(() => {});
command.parse();
console.log('Called with arguments:', command.args);
```

Has the following behavior

    $ ./example.js
    error: missing required argument 'source'
    $ ./example.js one
    Called with arguments: [ 'one' ]
    $ ./example.js one two
    error: too many arguments. Expected 1 argument but got 2.

If `.action(() => {});` is commented out, it has the following behavior:

    $ ./example.js 
    Called with arguments: []
    $ ./example.js one
    Called with arguments: [ 'one' ]
    $ ./example.js one two
    Called with arguments: [ 'one', 'two' ]

Which was surprising to me.  If this is intentional, perhaps a comment could be added to the [Specify the argument syntax section of `Readme.md`](https://github.com/tj/commander.js/blob/master/Readme.md#specify-the-argument-syntax) to warn users?  If not, perhaps it could be fixed?

Thanks for considering,
Kevin

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

## Problem

The number of command-arguments is only checked if there is an action handler. This means no checking for simple programs which fall-through to processing the results of the parsing in following code.

Fixes #1493

## Solution

Follow in the footsteps of the refactored tests for options. Both the option and command-argument tests were originally tied to the implementation of the action handler. They have now been separated out to be called where appropriate.

Check for missing required command-arguments, or excess command-arguments if enabled, in programs without an action handler.

## ChangeLog

- the number of command-arguments is now checked for programs without an action handler

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1576,11 +1573,17 @@ class Command extends EventEmitter {
...
 
-        this._actionHandler(args);
+      const commandEvent = `command:${this.name()}`;
+      if (this._actionHandler) {
+        checkForUnknownOptions();
+        this._actionHandler(getCheckedArguments());
         if (this.parent) this.parent.emit(commandEvent, operands, unknown); // legacy
       } else if (this.parent && this.parent.listenerCount(commandEvent)) {
         checkForUnknownOptions();
+        getCheckedArguments();
```
Comment (abetomo) [inline index.js:1586]: The name `getXXX` is a function to get something.

`this._actionHandler(getCheckedArguments());`.
For this code, it makes sense.

However, the code here does not use a return value.
I thought it was hard to understand what the 'get' was for.

**Review by abetomo — APPROVED** [review]
I commented on the naming, but the fix is LGTM.

File: index.js (hunk 1 above)
Comment (shadowspawn) [reply index.js:1586]: Thanks. I'll take another look. I started without it and added it to make the "get" usage make more sense. I'll try separating out the check and the variadic support since that is only needed in one case.

Comment (shadowspawn) [reply index.js]: Reworked. Longer but hopefully clearer.

Comment (abetomo) [reply index.js]: Thanks.

**Comment by shadowspawn** [comment]
Note for future readers. Missing command-arguments will now cause an error whether or not there is an action handler. This changes the behaviour for simple single command programs.

```js
program.argument('<file>');
program.parse();
```

```
$ pizza
error: missing required argument 'file'
```

If you want to just display the help if the user does not supply any arguments, you could check before calling parse like:

```js
if (process.argv.length === 2) program.help();
program.parse();
```

Also, see `.showHelpAfterError()` to change the default behaviour to include extra help.
